### ISSUE TITLE
Support CFF2 for VF hinting

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/psautohint#105]
```
$ psautohint '/home/nikolaus/Downloads/SourceSansVariable-Roman(1).otf'
ERROR: Unhandled exception occurred
Traceback (most recent call last):
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/__main__.py", line 707, in main
    hintFiles(options)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 212, in hintFiles
    hintFile(options, path, outpath, reference_master=False)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 221, in hintFile
    fontData = openFile(path, options)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 200, in openFile
    font = CFFFontData(path, font_format)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/otfFont.py", line 673, in __init__
    raise FontParseError("OTF font has no CFF table <%s>." % path)
psautohint.FontParseError: OTF font has no CFF table </home/nikolaus/Downloads/SourceSansVariable-Roman(1).otf>.
Traceback (most recent call last):
  File "/tmp/venv/bin/psautohint", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/__main__.py", line 707, in main
    hintFiles(options)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 212, in hintFiles
    hintFile(options, path, outpath, reference_master=False)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 221, in hintFile
    fontData = openFile(path, options)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/autohint.py", line 200, in openFile
    font = CFFFontData(path, font_format)
  File "/tmp/venv/lib64/python3.6/site-packages/psautohint/otfFont.py", line 673, in __init__
    raise FontParseError("OTF font has no CFF table <%s>." % path)
psautohint.FontParseError: OTF font has no CFF table </home/nikolaus/Downloads/SourceSansVariable-Roman(1).otf>.
```

**Comment by khaledhosny** [comment]
This is not supported indeed, and probably out of scope. The supported workflow right now is to hint the masters in a compatible way (by using `--reference` option), and combine them with a tool that knows how to build a CFF2 table.

**Comment by miguelsousa** [comment]
Wanting to hint or rehint a CFF2 table (which may contain un-variable as well as variable charstrings) seems like a valid case to me. I don't know what it would take to support it, or even if it's possible within the current architecture, but I think we need to consider it.
@readroberts @cjchapman what's your opinion?

**Comment by miguelsousa** [comment]
@readroberts please itemize here the changes required to get psautohint to be able to add hints to a variable CFF2 table.

**Comment by khaledhosny** [comment]
The way the C library currently works requires separate masters, a reference one that is hinted and the hints are copied to the test.

So if we were to support CFF2 without rewriting much of the C library, we would need a way to get separate CFF1 CharSrings corresponding to each master, translate to bez and hint them, then get merged bez string (the C lib has untested support for outputting merged bez glyphs) and convert it back to CFF2 CharString.

Seems like a lot of work to me for marginal benefit.

**Comment by readroberts** [comment]
@khaledhosny @msousa I have been looking at this, and think that it would no longer be so much work, and does have benefits.  I will expand more on this in a separate conversation.

**Comment by madig** [comment]
(Any news?)

**Comment by readroberts** [comment]
@madig Yes, I am now working on extending psautohint to directly hint a CFF2 VF font. This should be done and merged in the main branch within a  week or so.

**Comment by readroberts** [comment]
This is not supported with the latest version on the master branch.

**Comment by madig** [comment]
"Not" or "now"? 😁

**Comment by readroberts** [comment]
This was supposed to be 'now'.
