### ISSUE TITLE
running tests with `make check` fails with "Segmentation fault" 

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/psautohint#16]
this is python 3.6.3 on Linux
 
```
make -C ./tests PYTHONPATH="/home/clupo/Github/psautohint/build/lib.linux-x86_64-3.6"
make[1]: Entering directory '/home/clupo/Github/psautohint/tests'
	Testing data/source-code-pro/Medium/font.ufo
Makefile:21: recipe for target 'data/source-code-pro/Medium/font.tst' failed
make[1]: *** [data/source-code-pro/Medium/font.tst] Segmentation fault
make[1]: Leaving directory '/home/clupo/Github/psautohint/tests'
Makefile:43: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by khaledhosny** [comment]
No issue here with the same Python version on Linux as well. Can you get a backtrace of the segmentation fault?

**Comment by anthrotype** [comment]
I hope this helps (I also attached the dumped core if you want to inspect)
[core.zip](https://github.com/khaledhosny/psautohint/files/1503787/core.zip)

```
(psautohint-py3) clupo@clupo ~/Github/psautohint/tests (master) 
$ gdb `pyenv which python` core 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/clupo/.pyenv/versions/psautohint-py3/bin/python...done.

warning: core file may not match specified executable file.
[New LWP 22668]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python -m psautohint -all -qq -o data/source-code-pro/Medium/font.tst data/sour'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  GetNewPtLst () at libpsautohint/src/control.c:354
354	            newArray[i] = gPtLstArray[i];
(gdb) bt
#0  GetNewPtLst () at libpsautohint/src/control.c:354
#1  XtraClrs (e=e@entry=0x7f22428f3b48 <vm+15880>) at libpsautohint/src/control.c:370
#2  0x00007f22426cfb81 in StartNewColoring (e=e@entry=0x7f22428f3b48 <vm+15880>, hLst=hLst@entry=0x7f22428f8824 <vm+35556>, 
    vLst=vLst@entry=0x7f22428fd544 <vm+55300>) at libpsautohint/src/auto.c:708
#3  0x00007f22426d23be in AutoExtraColors (movetoNewClrs=false, soleol=soleol@entry=false, solWhere=solWhere@entry=2) at libpsautohint/src/auto.c:1147
#4  0x00007f22426d5fe4 in AddColorsInnerLoop (extracolor=<optimized out>, srcglyph=<optimized out>, fontinfo=<optimized out>)
    at libpsautohint/src/control.c:841
#5  AddColors (extracolor=<optimized out>, 
    srcglyph=0x564eec31b0e0 "%text\nsc 300 583 mt\n312 583 320 592 320 604 ct\n320 615 312 624 300 624 ct\n289 624 280 615 280 604 ct\n280 592 289 583 300 583 ct\ncp\n\n300 33 mt\n312 33 320 42 320 54 ct\n320 65 312 74 300 74 ct\n289 74 280"..., fontinfo=0x564eec2c9000) at libpsautohint/src/control.c:930
#6  AutoColorGlyph (fontinfo=fontinfo@entry=0x564eec2c9000, 
    srcglyph=srcglyph@entry=0x564eec31b0e0 "%text\nsc 300 583 mt\n312 583 320 592 320 604 ct\n320 615 312 624 300 624 ct\n289 624 280 615 280 604 ct\n280 592 289 583 300 583 ct\ncp\n\n300 33 mt\n312 33 320 42 320 54 ct\n320 65 312 74 300 74 ct\n289 74 280"..., extracolor=true) at libpsautohint/src/control.c:943
#7  0x00007f22426cf280 in AutoColor (fontinfo=fontinfo@entry=0x564eec2c9000, 
    srcbezdata=srcbezdata@entry=0x564eec31b0e0 "%text\nsc 300 583 mt\n312 583 320 592 320 604 ct\n320 615 312 624 300 624 ct\n289 624 280 615 280 604 ct\n280 592 289 583 300 583 ct\ncp\n\n300 33 mt\n312 33 320 42 320 54 ct\n320 65 312 74 300 74 ct\n289 74 280"..., fixStems=fixStems@entry=false, 
    debug=<optimized out>, extracolor=<optimized out>, changeChar=<optimized out>, roundCoords=false) at libpsautohint/src/ac.c:168
#8  0x00007f22426e2582 in AutoColorString (
    srcbezdata=srcbezdata@entry=0x564eec31b0e0 "%text\nsc 300 583 mt\n312 583 320 592 320 604 ct\n320 615 312 624 300 624 ct\n289 624 280 615 280 604 ct\n280 592 289 583 300 583 ct\ncp\n\n300 33 mt\n312 33 320 42 320 54 ct\n320 65 312 74 300 74 ct\n289 74 280"..., 
    fontinfodata=fontinfodata@entry=0x7f224225fd10 "AscenderHeight 709 AscenderOvershoot 12 BaselineOvershoot -12 BaselineYCoord 0 BlueFuzz 0 DescenderHeight -200 DescenderOvershoot -12 DominantH [80] DominantV [100] FlexOK false FontName SourceCodePro"..., dstbezdata=dstbezdata@entry=0x564eec327eb0 "", 
    length=length@entry=0x7ffd406b76c8, allowEdit=0, allowHintSub=1, roundCoords=0, debug=0) at libpsautohint/src/psautohint.c:353
#9  0x00007f22426ceb51 in autohint (self=<optimized out>, args=<optimized out>) at python/psautohint/_psautohint.c:147
#10 0x0000564eeb3ea468 in _PyCFunction_FastCallDict (kwargs=0x0, nargs=<optimized out>, args=0x564eec2e15f0, func_obj=0x7f22429ea318)
    at Objects/methodobject.c:234
#11 _PyCFunction_FastCallKeywords (func=func@entry=0x7f22429ea318, stack=stack@entry=0x564eec2e15f0, nargs=<optimized out>, kwnames=kwnames@entry=0x0)
    at Objects/methodobject.c:294
#12 0x0000564eeb47ba0e in call_function (pp_stack=pp_stack@entry=0x7ffd406b7860, oparg=oparg@entry=6, kwnames=kwnames@entry=0x0) at Python/ceval.c:4824
#13 0x0000564eeb47fb18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#14 0x0000564eeb47b65d in PyEval_EvalFrameEx (throwflag=0, f=0x564eec2e1308) at Python/ceval.c:753
#15 _PyEval_EvalCodeWithName (_co=0x7f2242a0a6f0, globals=globals@entry=0x7f2242a07048, locals=locals@entry=0x0, args=<optimized out>, argcount=1, 
    kwnames=kwnames@entry=0x0, kwargs=0x564eec238838, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7f2242a483b0, 
    qualname=0x7f2242a483b0) at Python/ceval.c:4153
#16 0x0000564eeb47b924 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7f224111d6a8) at Python/ceval.c:4965
#17 call_function (pp_stack=pp_stack@entry=0x7ffd406b7ae0, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#18 0x0000564eeb47fb18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#19 0x0000564eeb47abf1 in PyEval_EvalFrameEx (throwflag=0, f=0x564eec238698) at Python/ceval.c:753
---Type <return> to continue, or q <return> to quit---
#20 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=globals@entry=0x7f2242de02d0) at Python/ceval.c:4906
#21 0x0000564eeb47bb71 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7f224111d400) at Python/ceval.c:4948
#22 call_function (pp_stack=pp_stack@entry=0x7ffd406b7ca0, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#23 0x0000564eeb47fb18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#24 0x0000564eeb47b65d in PyEval_EvalFrameEx (throwflag=0, f=0x7f2242de5c50) at Python/ceval.c:753
#25 _PyEval_EvalCodeWithName (_co=_co@entry=0x7f2242a461e0, globals=globals@entry=0x7f2242de02d0, locals=locals@entry=0x7f2242de02d0, args=args@entry=0x0, 
    argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, 
    qualname=0x0) at Python/ceval.c:4153
#26 0x0000564eeb47c4f3 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, 
    locals=locals@entry=0x7f2242de02d0, globals=globals@entry=0x7f2242de02d0, _co=_co@entry=0x7f2242a461e0) at Python/ceval.c:4174
#27 PyEval_EvalCode (co=co@entry=0x7f2242a461e0, globals=globals@entry=0x7f2242de02d0, locals=locals@entry=0x7f2242de02d0) at Python/ceval.c:730
#28 0x0000564eeb479639 in builtin_exec_impl (module=<optimized out>, locals=0x7f2242de02d0, globals=0x7f2242de02d0, source=0x7f2242a461e0)
    at Python/bltinmodule.c:976
#29 builtin_exec (module=<optimized out>, args=<optimized out>) at Python/clinic/bltinmodule.c.h:283
#30 0x0000564eeb3ea468 in _PyCFunction_FastCallDict (kwargs=0x0, nargs=<optimized out>, args=0x564eec2437f8, func_obj=0x7f2242e619d8)
    at Objects/methodobject.c:234
#31 _PyCFunction_FastCallKeywords (func=func@entry=0x7f2242e619d8, stack=stack@entry=0x564eec2437f8, nargs=<optimized out>, kwnames=kwnames@entry=0x0)
    at Objects/methodobject.c:294
#32 0x0000564eeb47ba0e in call_function (pp_stack=pp_stack@entry=0x7ffd406b8000, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0) at Python/ceval.c:4824
#33 0x0000564eeb47fb18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#34 0x0000564eeb47b65d in PyEval_EvalFrameEx (throwflag=0, f=0x564eec243628) at Python/ceval.c:753
#35 _PyEval_EvalCodeWithName (_co=0x7f2242d25150, globals=globals@entry=0x7f2242d1f8b8, locals=locals@entry=0x0, args=<optimized out>, argcount=5, 
    kwnames=kwnames@entry=0x0, kwargs=0x564eec286da8, kwcount=0, kwstep=1, defs=0x7f2242d27218, defcount=5, kwdefs=0x0, closure=0x0, name=0x7f2242d236f0, 
    qualname=0x7f2242d236f0) at Python/ceval.c:4153
#36 0x0000564eeb47b924 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7f2242d15620) at Python/ceval.c:4965
#37 call_function (pp_stack=pp_stack@entry=0x7ffd406b8280, oparg=oparg@entry=5, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#38 0x0000564eeb47fb18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#39 0x0000564eeb47b65d in PyEval_EvalFrameEx (throwflag=0, f=0x564eec286bc8) at Python/ceval.c:753
#40 _PyEval_EvalCodeWithName (_co=0x7f2242d25390, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7f2242d230e0, argcount=2, 
    kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x7f2242d218e8, defcount=1, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0)
    at Python/ceval.c:4153
#41 0x0000564eeb47c56e in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7f2242d230e0, 
    argcount=<optimized out>, kws=kws@entry=0x0, kwcount=0, defs=0x7f2242d218e8, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:4174
#42 0x0000564eeb3b5364 in function_call (func=0x7f2242a42c80, arg=0x7f2242d230c8, kw=0x0) at Objects/funcobject.c:604
#43 0x0000564eeb382eda in PyObject_Call (func=func@entry=0x7f2242a42c80, args=args@entry=0x7f2242d230c8, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2261
#44 0x0000564eeb36ad41 in RunModule (modname=modname@entry=0x564eec1e02e0 L"psautohint", set_argv0=set_argv0@entry=1) at Modules/main.c:213
#45 0x0000564eeb36ba97 in Py_Main (argc=<optimized out>, argv=0x564eec1df010) at Modules/main.c:750
#46 0x0000564eeb34c9f1 in main (argc=8, argv=<optimized out>) at ./Programs/python.c:69
```

**Comment by anthrotype** [comment]
this is very weird...

I tried to compile without optimization to debug the issue with gdb (I passed CFLAGS="-O0" to `python setup.py build`) and now... the segfault disappeared!

Also, when I build psautohint with the built-in python3.5 that comes with my Debian, it does _not_ segfault, whereas when I build with python3.6 that I compiled from source with pyenv, running the test fails with segmentation fault.

It turns out that, for my self-compiled python3.6, the default level of optimization is -O3 (distutils passes the same cflags used to build python when compiling extension modules). Whereas with the Debian python3.5 it's -O2. But if I recompile with CFLAGS="-O3" also the latter fails with segfault.

I suspect that there must be something wrong in a program if it segfaults depending on the compiler optimization level.

Btw, my gcc --version is `gcc (Debian 6.3.0-18) 6.3.0 20170516`

**Comment by anthrotype** [comment]
I found a similar thread where they say this may be related to 

> vectorisation, which is switched on with gcc -O3

https://github.com/samtools/htslib/issues/400#issuecomment-233366825

Indeed, if I pass `CFLAGS="-fno-tree-vectorize"` it works even with `-O3` optimization.

@khaledhosny maybe we should add that flag to the extension's `extra_compile_args`?

**Comment by khaledhosny** [comment]
Thanks for debugging this, if you can send a PR I'll merge it.

**Comment by anthrotype** [comment]
this bug has resurfaced after we split off the libpsautohint static library so we could link it with both the extension module and the autohintexe executable.
We need to pass the same `-fno-tree-vectorize` when compiling the static library, not just the extension module, otherwise one gets segfault when psautohint is compiled with gcc -O3.
