### ISSUE TITLE
Version 1.7.0b1 is broken

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#61]
I just installed version 1.7.0b1 on a new venv and this is what I get.

```
$ psautohint tests/data/source-code-pro/Black/font.ufo
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/msousa/Tools/psautohint/bin/psautohint", line 11, in <module>
    sys.exit(main())
  File "/Users/msousa/Tools/psautohint/lib/python2.7/site-packages/psautohint/__main__.py", line 708, in main
    hintFiles(options)
  File "/Users/msousa/Tools/psautohint/lib/python2.7/site-packages/psautohint/autohint.py", line 318, in hintFiles
    outpath = options.outputPaths[i]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I'm guessing that this wasn't caught by the CI because the tests bypass `__main__.py`

**Comment by khaledhosny** [comment]
I feared this is going to happen. Fixing this and working on tests for the command line shortly.
